# @package _global_

project_name: GEN_CD
log_directory: lightning_logs
mode: train # train | test | validate_all

id:
  version: "CD__AudioLDM_concat_mix_P=1.2_1.2_attn-8_16_32"
  name: ""

model:
  class_cond: True
  concat: True
 
  img_resolution: 64                     # Image resolution at input/output.
  in_channels: 2                       # Number of color channels at input.
  out_channels: 1
  label_dim: 4
  augment_dim: 0  # Augmentation label dimensionality, 0 = no augmentation

  model_channels: 256  # Base multiplier for the number of channels
  channel_mult: [1, 2, 2, 2]  # Per-resolution multipliers for the number of channels
  channel_mult_emb: 4  # Multiplier for the dimensionality of the embedding vector
  num_blocks: 4  # Number of residual blocks per resolution
  attn_resolutions: [8,16,32]  # List of resolutions with self-attention
  dropout: 0.10  # Dropout probability of intermediate activations
  label_dropout: 0  # Dropout probability of class labels for classifier-free guidance

  embedding_type: positional  # Timestep embedding type: 'positional' for DDPM++, 'fourier' for NCSN++
  channel_mult_noise: 1  # Timestep embedding size: 1 for DDPM++, 2 for NCSN++
  encoder_type: standard  # Encoder architecture: 'standard' for DDPM++, 'residual' for NCSN++
  decoder_type: standard  # Decoder architecture: 'standard' for both DDPM++ and NCSN++
  resample_filter: [1, 1]  # Resampling filter: [1,1] for DDPM++, [1,3,3,1] for NCSN++
  num_heads: 1


train_dataset:
  _target_: main.data.TracksDataset
  audio_files_dir: "dataset/slakh2100_44100/train"
  sr: 44100
  channels: 1
  min_duration: 6.1
  max_duration: 640.0
  aug_shift: True
  sample_length: 264600
  stems: ['bass', 'drums', 'guitar', 'piano']

val_dataset:
  _target_: main.data.TracksDataset
  audio_files_dir: "dataset/slakh2100_44100/validation"
  sr: 44100
  channels: 1
  min_duration: 6.1
  max_duration: 640.0
  aug_shift: False #True
  sample_length: 264600
  stems: ['bass', 'drums', 'guitar', 'piano']

datamodule:
  batch_size: 32
  num_workers: 8
  pin_memory: True



audio_samples_logger:
  _target_: main.audio_ctm.ClassCond_GEN_2D_TrackSampleLoggerCTM
  num_items: 2 #10
  channels: 1
  img_resolution: 64
  sampling_rate: 44100
  length: 264600
  sampler:
    # - heun 
    - onestep
    - cm_multistep_cd 
    # - heun
    # - exact
  check_ctm_denoising_ability: True
  clip_output: False
  clip_denoised: False
  denoise_steps_to_log:
    # - 10
    - 1
    - 2
    # - 10
    # - 1
  stems: ['bass', 'drums', 'guitar', 'piano']
  models_to_log:
    # - teacher_model
    - net 
    - net
    # - ema_models[0]
    # - ema_models[1]

  # args for metrics calculation
  model_to_calculate_metrics: net
  sampler_to_calculate_metrics: cm_multistep_cd #heun
  steps_to_calculate_metrics: 1



callbacks:
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar

  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 1




trainer:
  accelerator: cuda
  devices: [0, 1, 2] # Set `1` to train on GPU, `0` to train on CPU only, and `-1` to train on all GPUs, default `0`
  precision: "bf16" # Precision used for tensors, default `32`
  min_epochs: 0
  max_epochs: 1000
  max_steps: 600000
  accumulate_grad_batches: 4
  enable_model_summary: False
  log_every_n_steps: 10 # Logs metrics every N batches
  check_val_every_n_epoch: null
  val_check_interval: #1000
  limit_val_batches: 55
  limit_train_batches: 
  strategy: ddp
  num_sanity_val_steps: 0

resume_from_checkpoint: 



optim:
    grad_clip: null
    weight_decay: 0
    lr: 1.e-5
    betas: [0.9,0.999]
    eps: 1.e-8
    amsgrad: False
    optimizer : radam
    warmup_epochs: 1

diffusion:
    preconditioning: cd # ctm | ct | vp | ve | edm

    # cm_train_defaults
    target_ema_mode: "fixed"                                                    # "fixed" | "adaptive" 
    scale_mode: "fixed"                                                         # "fixed" | "progressive"
    # total_training_steps: 600000
    start_scales: 18                                                            # cifar10 18  | Imagenet 40
    end_scales: 18                                                              # cifar10 18  | Imagenet 40
    distill_steps_per_iter: 50000                                               # only if scale_mode == "progdist"
    teacher_model_path: lightning_logs/GEN_diffusion_model/2025-02-02T00-06-03__Diffusion_AudioLDM_concat_mix_P=1.2_1.2_attn-8_16_32/checkpoints/epoch=214-valid_loss=0.4414.ckpt
    model_path:                                                                 ## ??? not sure what is this
    training_mode: "cd"                                                        ## do not change this!!!
    num_heun_step: 17                                                           # cifar10 17 IMagenet 39
    num_heun_step_random: True
    loss_norm: "mse"
    use_fp16: False
    ema_rate: []
        # - 0.999
        # - 0.9999
    start_ema: 0.999
    

    # Network architecture
    # edm_nn_ncsn: False
    # edm_nn_ddpm: True                                                           # if data_name == 'cifar10' else False,
    linear_probing: False       # ???
    target_subtract: False

    # model_and_diffusion_defaults
    schedule_sampler: "uniform"                                                 # | "uniform" | "lognormal"
    # sigma_min: 0.002
    # sigma_max: 80.0
    # sigma_data: 0.5
    # rho: 7

    sigma_min: 0.0001
    sigma_max: 80.0 #15.0
    sigma_data: 1.0
    rho: 9



    weight_schedule: uniform
    weight_schedule_multiplier: 1.0
    diffusion_weight_schedule: "karras_weight"
    rescaling: False


    # ctm_loss_defaults

    # CTM hyperparams
    consistency_weight: 1.0
    time_continuous: False
    heun_step_strategy: 'weighted'
    heun_step_multiplier: 1.0
    self_learn: False
    self_learn_iterative: False
    inner_parametrization: 'edm'
    outer_parametrization: 'euler'
    ctm_estimate_outer_type: 'target_model_sg'
    ctm_estimate_inner_type: 'model'
    ctm_target_matching: False
    ctm_target_inner_type: 'target_model_sg'
    sample_s_strategy: 'uniform'                                                # 'smallest' | 'uniform' 
    
    save_png: False
    save_period: 0
    

    # DSM hyperparams
    diffusion_training: True
    apply_adaptive_weight: False
    apply_adaptive_weight_for_audio: True
    denoising_weight: 1.0
    diffusion_mult: 0.7
    diffusion_schedule_sampler: "halflognormal" # ???
    diffusion_training_frequency: 1.
    p_mean: -1.2
    p_std: 1.2

    ### eval defaults ???
    large_log: False

    # # args to accomodate sound_ctm feature extracting idea
    # match_point: z0 # zs | z0
    # loss_norm: mse
    # # unet_mode: full